### ISSUE TITLE
Error installing on Drupal 8.2

### ISSUE THREAD

**Issue by mccrodp** [RoySegall/rethinkdb#23]
Hey @RoySegall - I'm not sure if it's Drupal version specific, but I got:

```
Error: Call to undefined function r\connect() in /var/www/html/modules/rethinkdb/src/RethinkDB.php on line 53 #0 /var/www/html/core/lib/Drupal/Component/DependencyInjection/Container.php(268): Drupal\rethinkdb\RethinkDB->__construct(Object(Drupal\Core\Config\ConfigFactory))
#1 /var/www/html/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService(Array, 'rethinkdb')
```

**Comment by RoySegall** [comment]
Hmmm I think it's because you did not run the composer manager - https://github.com/RoySegall/rethinkdb/blob/8.x-1.x/.travis.yml#L68

I forgot to update the read me file on how to do a proper install. I'll get to this once the work on DrupalCamp will be less intense.

**Comment by mccrodp** [comment]
Of course, rookie error on my part, haha. Thank you. Cool, good luck with that.

I'm looking at pushing data to RethinkDB, is that something worth writing a PR on this module or better placed in a separate module?

**Comment by RoySegall** [comment]
In the modules directory we have modules to show different approach to tackle this issue. One module handle with messages stored on RethinkDB and access through the entity API. Another one is how to replicate entities created in RethinkDB and the third module show how to create push notification from nodeJS to pusher and how to integrate with it.

Another plan was to set up a backend that will manage geo-location cha rooms - https://github.com/RoySegall/interestingBackend

The drupal backend is ready but due to time limitation I won't be able to complete the node js and react parts. Instead i'm planning on doing a small electron app that will intercept any watchdog errors and push it to the user. This will be presented in the DrupalCamp on how to do it.

**Comment by RoySegall** [comment]
So the way I'm going to solve this one is:
1. Remove the creation of DB from the hook_install()
2. Add a method to validate the connection
3. Add a link under the connection settings to add the DB.

**Comment by RoySegall** [comment]
@mccrodp I improved the installation process. There are some more fixes I need push to improve the module but you suppose to be ready to go.

**Comment by mccrodp** [comment]
Awesome, hope to give this a shot soon. Your description in https://github.com/RoySegall/rethinkdb/issues/23#issuecomment-246275948 sounds great :) Good job!
